"""p0_collector_runs

Revision ID: 527069a609a0
Revises: 0003_add_analysis_suggestion
Create Date: 2026-07-20 10:15:52.401239
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '527069a609a0'
down_revision: Union[str, None] = '0003_add_analysis_suggestion'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collector_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collector_name', sa.String(length=128), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('fetched_raw', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('analyzed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('keywords_word_key', 'keywords', type_='unique')
    op.drop_constraint('regions_code_key', 'regions', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('regions_code_key', 'regions', ['code'])
    op.create_unique_constraint('keywords_word_key', 'keywords', ['word'])
    op.drop_table('collector_runs')
    # ### end Alembic commands ###
