"""p1_fulltext_keywords_hebei_sources

Revision ID: c0769f234982
Revises: 527069a609a0
Create Date: 2026-07-20 13:38:32.626374
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0769f234982'
down_revision: Union[str, None] = '527069a609a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opinions', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opinions', 'search_vector')
    # ### end Alembic commands ###
